[email]
from_email = "vigneshsapavat11@gmail.com"
app_password = "kmcfregjdseaihwn"

[database]
host = "aws-0-ap-south-1.pooler.supabase.com"
database = "postgres"
user = "postgres.vigneshsapavat11-oss"
password = "Vijayvignesh@123"
port = "6543"
